networks:
  benchmark-network:
    ipam:
      config:
        - subnet: "172.16.40.0/24"
services:
#  client-leader:
#    depends_on:
#      - genesis
#      - replica
#    build:
#      context: ./
#      dockerfile: client.Dockerfile
#    entrypoint: ./client
#    command: --knownAddr genesis:8080 --nodeToCrashAddr replica-to-crash:8080 --isLeader
#    image: benchmarkclient
#    tty: true
#    networks:
#      benchmark-network:
#    volumes:
#      - /var/log/oncetree:/app/logs/


  client:
    depends_on:
      - genesis
      - replica
    build:
      context: ./
      dockerfile: client.Dockerfile
    entrypoint: ./client
    command: --knownAddr genesis:8080 --nodeToCrashAddr replica-to-crash:8080
    image: benchmarkclient
    tty: true
    networks:
      benchmark-network:
    deploy:
      mode: replicated
      replicas: 5
    volumes:
      - /var/log/oncetree:/app/logs/

  genesis:
    build:
      context: ./
      dockerfile: replica.Dockerfile
    image: benchmarkreplica
    tty: true
    networks:
      benchmark-network:
        ipv4_address: "172.16.40.2"
    volumes:
      - /var/log/oncetree:/app/logs/

  replica-to-crash:
    depends_on:
      - genesis
    build:
      context: ./
      dockerfile: replica.Dockerfile
    entrypoint: ./replica
    command: --knownAddr genesis:8080
    image: benchmarkreplica
    tty: true
    networks:
      benchmark-network:
    volumes:
      - /var/log/oncetree:/app/logs/

  replica:
    depends_on:
      - genesis
    build:
      context: ./
      dockerfile: replica.Dockerfile
    entrypoint: ./replica
    command: --knownAddr genesis:8080
    image: benchmarkreplica
    tty: true
    networks:
      benchmark-network:
    deploy:
      mode: replicated
      replicas: 13
    volumes:
      - /var/log/oncetree:/app/logs/
