services:
  client:
    build:
      context: ./
      dockerfile: client.Dockerfile
    image: benchmarkclient
    tty: true
  replica:
    build:
      context: ./
      dockerfile: replica.Dockerfile
    image: benchmarkreplica
    tty: true
