networks:
  benchmark-network:
    ipam:
      config:
        - subnet: "172.16.40.0/24"
services:
  crash-client:
    depends_on:
      - genesis
      - replica
    build:
      context: ./
      dockerfile: client.Dockerfile
    entrypoint: ./client
    command: --knownAddr genesis:8080 --nodeToCrashAddr crash-replica:8080 --isLeader --writer
    image: benchmarkclient
    tty: true
    networks:
      benchmark-network:
    volumes:
      - /var/log/oncetree:/app/logs/


  writer:
    depends_on:
      - genesis
      - replica
    build:
      context: ./
      dockerfile: client.Dockerfile
    entrypoint: ./client
    command: --knownAddr genesis:8080 --nodeToCrashAddr crash-replica:8080 --writer
    image: benchmarkclient
    tty: true
    networks:
      benchmark-network:
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - /var/log/oncetree:/app/logs/


  reader:
    depends_on:
      - genesis
      - replica
    build:
      context: ./
      dockerfile: client.Dockerfile
    entrypoint: ./client
    command: --knownAddr genesis:8080 --nodeToCrashAddr crash-replica:8080 --reader
    image: benchmarkclient
    tty: true
    networks:
      benchmark-network:
    deploy:
      mode: replicated
      replicas: 9
    volumes:
      - /var/log/oncetree:/app/logs/

  genesis:
    build:
      context: ./
      dockerfile: replica.Dockerfile
    image: benchmarkreplica
    tty: true
    networks:
      benchmark-network:
        ipv4_address: "172.16.40.2"
    volumes:
      - /var/log/oncetree:/app/logs/

  crash-replica:
    depends_on:
      - genesis
    build:
      context: ./
      dockerfile: replica.Dockerfile
    entrypoint: ./replica
    command: --knownAddr genesis:8080
    image: benchmarkreplica
    tty: true
    networks:
      benchmark-network:
    volumes:
      - /var/log/oncetree:/app/logs/

  replica:
    depends_on:
      - genesis
    build:
      context: ./
      dockerfile: replica.Dockerfile
    entrypoint: ./replica
    command: --knownAddr genesis:8080
    image: benchmarkreplica
    tty: true
    networks:
      benchmark-network:
    deploy:
      mode: replicated
      replicas: 13
    volumes:
      - /var/log/oncetree:/app/logs/
